"""create applications table

Revision ID: 8c8ba89fb7cd
Revises: abc0a75db3ae
Create Date: 2026-09-26 00:02:39.443307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8ba89fb7cd'
down_revision: Union[str, Sequence[str], None] = 'abc0a75db3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'OA', 'RECRUITER_SCREEN', 'INTERVIEW', 'FINAL_ROUND', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('platform', sa.Enum('LINKEDIN', 'HANDSHAKE', 'INDEED', 'COMPANY_WEBSITE', 'REFERRAL', 'CAREER_FAIR', 'OTHER', name='applicationplatform'), nullable=True),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('skills_aligned', sa.String(length=500), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
